name: Lets win that bro

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  condicao_variaveis:
    runs-on: ubuntu-latest
    env: 
      APP_NODE: test
    steps:
      - name: Impressao de variaveis
        env:
          LOCAL_FLAG: enabled
        run: |
          echo "${{env.APP_NODE}}"
          echo "$LOCAL_FLAG"
          echo "APP_NODE: ${{env.APP_NODE}}, LOCAL_FLAG: $LOCAL_FLAG"
          echo 'APP_NODE: ${{env.APP_NODE}}, LOCAL_FLAG: $LOCAL_FLAG'
      - name: Usando condicao
        if: github.event_name == 'push'
        run: echo 'Rodando apenas no push'
  bem_custom:
    runs-on: ubuntu-latest
    env: 
      ADMIN_USER: nathanael
    steps:
      - name: Log de algumas variaveis
        run: |
          echo "${{env.ADMIN_USER}}, dono do repositorio ${{github.repository_owner}}
          
      - name: executar somente com workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "fds"
      
    
    